### ISSUE TITLE
Inform user about volume adjustment mode

### ISSUE THREAD

**Issue by dansvend** [equinor/earplug-test#83]
Inform whether the volume adjustment buttons are in fine tune mode.

**Comment by dansvend** [comment]
@KaterynaBasik This is ready for testing in `2024.905.122`.

**Comment by KaterynaBasik** [comment]
Tested in 2024.905.122. 
The text informing  about different modes is displayed clearly and at the correct moment during volume adjustment

**Comment by dansvend** [comment]
> Tested in 2024.905.122. The text informing about different modes is displayed clearly and at the correct moment during volume adjustment

Thanks for testing 🙏
