### ISSUE TITLE
Add app version to telemetry

### ISSUE THREAD

**Issue by dansvend** [equinor/earplug-test#88]
Add `app-version` as a custom property to all events logged to Application Insights.

**Comment by QiJin-Bouvet** [comment]
Tested with the build 2024.100.3126.
app-version is shown in the AppInsights Logs.

![image](https://github.com/user-attachments/assets/4be2c64b-ae32-4456-976f-0bfd188a1637)

**Comment by dansvend** [comment]
Awesome! Thanks for testing @QiJin-Bouvet 🙏
